services:
  chapter04:
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      dockerfile: ../.docker/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /com.docker.devenvironments.code
      - vscode-server:/root/.vscode-server
    working_dir: /com.docker.devenvironments.code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  vscode-server: