services:
  earthquakes:
    user: arkaikus
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=arkaikus
        - USER_ID=1000
        - GROUP_ID=1000
    working_dir: /home/arkaikus/earthquakes
    volumes:
      - .:/home/arkaikus/earthquakes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  vscode-server:
