services:
  earthquakes:
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /earthquakes
    volumes:
      - .:/earthquakes
      - vscode-server:/root/.vscode-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  vscode-server:
